setwd("C:/Users/danie/Desktop/Programacion/RWorks")
# a)
1-sum(dpois(0:9,7.2))
1-ppois(9,7.2)
# b)
ppois(8,7.2)-ppois(2,7.2)
# c)
qpois(0.75,7.2)
ppois(9,7.2)
# d)
qpois(0.05,7.2)
# e)
set.seed(100)
muestra <- rpois(1000,7.2)
var(muestra)
set.seed(30)
muestra <-rpois(500, 7.2)
valor = max(muestra)-1
h<-hist(muestra,col = "orange",freq = FALSE)
points(0:valor,dpois(0:valor,7.20),col = "green")
lines(0:valor,dpois(0:valor,7.20),col = "yellow")

muestra2 <- cumsum(h$counts)/500
plot(h$mids, muestra2, type= "h", lwd = 5, xlab = "muestra aleatoria", ylab = "frecuencia relativa")
points(h$mids,ppois(h$mids,7.2),col = "blue", type = "b")
